# Generated by Django 4.2.5 on 2023-09-26 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feed", "0003_ticket_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="ticket",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="feed.ticket"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
