# Generated by Django 4.2.5 on 2023-09-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0004_review_ticket_review_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tickets/"),
        ),
    ]
